---
driver:
  name: ec2
  aws_ssh_key_id: TestKitchen
  region: us-east-1
  availability_zone: b
  subnet_id: subnet-cc4bdbe3
  instance_type: t1.micro
  image_id: ami-e2c45a98
  security_group_ids: ["sg-a9fe44dd"]
  retryable_tries: 120

provisioner:
  name: chef_zero

verifier:
  name: inspec

transport:
  ssh_key: /Users/tomfinch/.ssh/TestKitchen.pem

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[tomskillerwebsite::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
